### ISSUE TITLE
redstone plate

### ISSUE THREAD

**Issue by dotsofdarkness** [TheLimePixel/Modern-Skyblock-Classic#5]
there is a recipe for redstone plates in the advanced rockery rolling machine that only takes water

**Comment by TheLimePixel** [comment]
In JEI? If so, I can't find it
![image](https://user-images.githubusercontent.com/25333164/58963419-64199180-87ad-11e9-802d-c5b4873bb8cc.png)

**Comment by dotsofdarkness** [comment]
![2019-06-06_09 45 05](https://user-images.githubusercontent.com/41033881/58997407-e05cb500-883f-11e9-8762-5225d6b96a4f.png)

**Comment by Ozzymud** [comment]
I see the proper recipe as well, @dotsofdarkness, you had "comb" typed into jei, what path did you click on to get the the plate recipe you are viewing?

**Comment by dotsofdarkness** [comment]
i didn't search the recipe i viewed the recipe for the redstone plate that was in the output but here it is in JEI
![2019-06-13_13 12 08](https://user-images.githubusercontent.com/41033881/59401099-f852ac80-8ddc-11e9-8f65-6fc0f22474b1.png)
![2019-06-13_13 12 18](https://user-images.githubusercontent.com/41033881/59401100-f852ac80-8ddc-11e9-9ed3-70aed39f35df.png)

**Comment by Ozzymud** [comment]
Right, what does it show when you click it in JEI? What I see strange in the original 2 images of this thread is the center tab. I see the same thing EmosewaPixel sees when I use jei with the IE press as the center tab. Your shot shows some other machine which might indicate the display is where the bug is. 

![Image1](https://user-images.githubusercontent.com/6426344/59402161-20e19480-8d52-11e9-8395-82340044e066.png)

Loading the pack now to see what it looks like for me getting a recipe from the output of the rolling machine.

**Comment by Ozzymud** [comment]
Aha, I made a creative world, set up a rolling machine, added water, turned it on and guess what,,, I made a plate from just water. Pressing R on the plate in the output showed me the following:  

![2019-06-12_20 52 41](https://user-images.githubusercontent.com/6426344/59402662-42438000-8d54-11e9-8c75-573bb3720827.png)

**Comment by Ozzymud** [comment]
And now looking at JEI closer... there are two redstone plates. Clicking the 1st from ContentTweaker  shows the topmost image in this post... Clicking the 2nd from TechReborn in JEI shows the erroneous recipe that indeed only needs water to create (tested with only water in the rolling machine).

**Comment by TheLimePixel** [comment]
The problem is that the plate recipes are generated from ingots, but there isn't a redstone ingot, hence you have an empty input.
